### ISSUE TITLE
Multiple concurrent sessions are not supported

### ISSUE THREAD

**Issue by mgrybyk** [RafalSkorka/wdio-geckodriver-service#1]
Hello,

try running more than one tests in parallel with geckodriver, it fails with error `Session is already started`.

see https://github.com/mozilla/geckodriver/issues/1213

**Comment by jcollum-autodesk** [comment]
Thanks for reporting this @mgrybyk

**Comment by RafalSkorka** [comment]
Do you know if it's possible to know which runner instance is running from within the custom service?
Otherwise I would need to choose a random port for each instance and that could randomly fail on collision.

**Comment by mgrybyk** [comment]
wdio starts geckodriver service only once even if we run multiple tests in parallel. 
Anyway I think I've misunderstood your question, if you talking about some extra port that geckodriver needs, then random port is fine

**Comment by RafalSkorka** [comment]
Reading the mentioned geckodriver issue it's not possible to have a single geckodriver controlling multiple firefox instances. So I need to run multiple geckodrivers instances on different ports unfortunately.
My hope was though, I can still let users choose a "base" port like 4444 and then the first runner would use it, the second would use 4445 and so on.
If I don't find any solution to find out which instance it would be then I'll fall back to a random port and write in the readme that specifying a port number will limit the concurrency to 1.

**Comment by mgrybyk** [comment]
I'd another another option to toggle an ability of running gecko driver service as a a launcher (spawn only one instance for all tests) or as a service (spawn instance per spec file).

If the port is not specified in wdio it is set to 4444.

As far as each spec file is spawned in separate child process there is no way to understand if there are any other processes are running or not and what ports are used.

**Comment by RafalSkorka** [comment]
I have released new version which should support concurrent sessions.

**Comment by mgrybyk** [comment]
Thank you @RafalSkorka

Closing the issue then
